version: "3.7"
services:

  web_main:
    image: ecss/web_main:main
    container_name: web_main
    volumes:
        - web_main_data:/home/node/app/media
    restart: unless-stopped
    depends_on:
      - db_mongo
    env_file:
      - ./env/web_main.env
    environment:
      - PORT=3000
      - PAYLOAD_PUBLIC_SERVER_URL=https://society.ecs.soton.ac.uk
      - NEXT_PUBLIC_SERVER_URL=https://society.ecs.soton.ac.uk

  web_sotonverify:
    image: ecss/web_sotonverify:main
    container_name: web_sotonverify
    restart: unless-stopped
    env_file:
      - ./env/web_sotonverify.env
    environment:
      - PORT=3000
      - NEXTAUTH_URL=https://sotonverify.link/

  web_teamreg:
    image: ecss/web_teamreg:main
    container_name: web_teamreg
    restart: unless-stopped
    env_file:
      - ./env/web_teamreg.env
    environment:
      - PORT=3000
      - NEXTAUTH_URL=https://society.ecs.soton.ac.uk/hackathon/api/auth
      - BASE_URL=https://society.ecs.soton.ac.uk/hackathon

  bot_sotonverify:
    image: ecss/bot_sotonverify:main
    container_name: bot_sotonverify
    restart: unless-stopped
    env_file:
      - ./env/bot_sotonverify.env
    environment:
      - API_URL=https://sotonverify.link
      - DISPLAY_URL=https://sotonverify.link

  db_mongo:
    image: mongo
    container_name: db_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_mongo_password
    secrets:
      - db_mongo_username
      - db_mongo_password
    volumes:
      - mongodb_data:/data/db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 5

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: unless-stopped
    command: --base-url=/service/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

secrets:
  db_mongo_password:
    file: ./env/db_mongo_password.txt
  db_mongo_username:
    file: ./env/db_mongo_username.txt

volumes:
  web_main_data:
  mongodb_data:
  portainer_data:
  caddy_data:
  caddy_config:
