# version: "3.9"
services:

  web_main:
    image: ecss/web_main:main
    container_name: web_main
    networks:
      soton_network:
        ipv4_address: 10.5.0.5
    volumes:
        - web_main_data:/home/node/app/media
    restart: unless-stopped
    depends_on:
      - db_mongo
    env_file:
      - ./env/web_main.env
    environment:
      - PORT=3000
      - PAYLOAD_PUBLIC_SERVER_URL=https://society.ecs.soton.ac.uk
      - NEXT_PUBLIC_SERVER_URL=https://society.ecs.soton.ac.uk

  web_sotonverify:
    image: ecss/web_sotonverify:main
    container_name: web_sotonverify
    restart: unless-stopped
    networks:
      soton_network:
        ipv4_address: 10.5.0.6
    env_file:
      - ./env/web_sotonverify.env
    environment:
      - PORT=3000
      - NEXTAUTH_URL=https://sotonverify.link/

  # web_teamreg:
  #   image: ecss/web_teamreg:main
  #   container_name: web_teamreg
  #   restart: unless-stopped
  #   networks:
  #     soton_network:
  #       ipv4_address: 10.5.0.8
  #   env_file:
  #     - ./env/web_teamreg.env
  #   environment:
  #     - PORT=3000
  #     - NEXTAUTH_URL=https://society.ecs.soton.ac.uk/hackathon/api/auth
  #     - BASE_URL=https://society.ecs.soton.ac.uk/hackathon

  web_booking:
    image: ecss/web_booking:main
    container_name: web_booking
    networks:
      soton_network:
        ipv4_address: 10.5.0.8
    env_file:
      - ./env/web_booking.env
    environment:
      - PORT=3000
      - NEXTAUTH_URL=https://society.ecs.soton.ac.uk/winterball
      - BASE_URL=https://society.ecs.soton.ac.uk/winterball

  bot_sotonverify:
    image: ecss/bot_sotonverify:main
    container_name: bot_sotonverify
    restart: unless-stopped
    env_file:
      - ./env/bot_sotonverify.env
    environment:
      - API_URL=https://sotonverify.link
      - DISPLAY_URL=https://sotonverify.link

  db_mongo:
    image: mongo
    container_name: db_mongo
    networks:
      soton_network:
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 5

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    networks:
      soton_network:
        ipv4_address: 10.5.0.7
    restart: unless-stopped
    command: --base-url=/service/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5433:5432
    networks:
      soton_network:
    volumes:
      - ./pgdata:/var/lib/postgresql
      # - ./init:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  
  # app:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt

  # caddy:
  #   image: caddy
  #   container_name: caddy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config

networks:
  soton_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  web_main_data:
  mongodb_data:
  portainer_data:
  caddy_data:
  caddy_config:
  postgres_data:
